### ISSUE TITLE
INFOGRAFIA DE HILOS_Sandy_Marissa_Garcia_Santiago_4BS

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/infografia-de-hilos-SandyMarissaGs#2]
[INFOGRAFIA DE HILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-SandyMarissaGs/files/15044606/INFOGRAFIA.DE.HILOS.pdf)

**Comment by AmeliReyesHernandez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
