### ISSUE TITLE
infografía 

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/infografia-de-hilos-SandyMarissaGs#3]
[infografia-de-hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-SandyMarissaGs/files/15046999/infografia-de-hilos.pdf)
infografía de EDGAAR AXEL SANDOVAL HERNANDEZ

**Comment by josealfredo79** [comment]
La calificacion????

**Comment by josealfredo79** [comment]
Se debe asignar una calificacion..19
